//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EURIS.Entities
{
    using EURIS.Service.Common.ServicesCommon;
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog : ICatalog
    {
        public Catalog()
        {
            this.ProductCatalog = new HashSet<ProductCatalog>();
        }
    
        public int CatalogId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ProductCatalog> ProductCatalog { get; set; }
    }
}
