//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EURIS.Entities
{
    using EURIS.Service.Common.ServicesCommon;
    using System;
    using System.Collections.Generic;


    public partial class ProductCatalog : IProductCatalog
    {
        public int ProductCatalogId { get; set; }
        public int ProductId { get; set; }
        public int CatalogId { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual Product Product { get; set; }
    }
}
